import {
  listOutline,
  fastFood,
  female,
  bookmark,
  keySharp,
  giftSharp,
  snowSharp,
  subwaySharp,
  sunnySharp,
  tennisball,
  callSharp,
  bodySharp,
  bicycleSharp,
  build,
  barbellSharp,
  airplaneSharp,
  alarmSharp,
  alertSharp,
  bandageSharp,
  barChartSharp,
  desktopSharp,
  fishSharp,
  gameControllerSharp,
  home,
  man,
  lockClosedSharp,
  megaphoneSharp,
  newspaper,
  pawSharp,
  boatSharp,
  partlySunnySharp,
  schoolSharp,
  storefrontSharp,
  thermometerSharp,
  umbrellaSharp,
  woman,
  water,
  musicalNotesSharp,
  moonSharp,
  peopleSharp,
  telescopeSharp,
  thunderstormSharp,
  volumeMuteSharp,
  wifiSharp,
  settingsSharp,
  squareSharp,
  starSharp,
  homeSharp,
  cameraSharp,
  triangleSharp,
} from "ionicons/icons";

// export const bgColorCateList = [
//   { codeColor: "bg-[#EA3C30]" },
//   { codeColor: "bg-[#E48E13]" },
//   { codeColor: "bg-[#F2C001]" },
//   { codeColor: "bg-[#1DB64B]" },
//   { codeColor: "bg-[#579FD9]" },
//   { codeColor: "bg-[#0A72E8]" },
//   { codeColor: "bg-[#DC4163]" },
//   { codeColor: "bg-[#BD71D3]" },
//   { codeColor: "bg-[#967B52]" },
//   { codeColor: "bg-[#5B6575]" },
//   { codeColor: "bg-[#CE9E95]" },
// ];
export const colorCateData = [
  { codeColor: "#EA3C30" },
  { codeColor: "#E48E13" },
  { codeColor: "#F2C001" },
  { codeColor: "#1DB64B" },
  { codeColor: "#579FD9" },
  { codeColor: "#0A72E8" },
  { codeColor: "#DC4163" },
  { codeColor: "#BD71D3" },
  { codeColor: "#967B52" },
  { codeColor: "#5B6575" },
  { codeColor: "#CE9E95" },
];
export const iconCateData = [
  { icon: listOutline },
  { icon: bookmark },
  { icon: keySharp },
  { icon: giftSharp },
  { icon: fastFood },
  { icon: female },
  { icon: snowSharp },
  { icon: subwaySharp },
  { icon: sunnySharp },
  { icon: tennisball },
  { icon: callSharp },
  { icon: bodySharp },
  { icon: bicycleSharp },
  { icon: build },
  { icon: barbellSharp },
  { icon: airplaneSharp },
  { icon: alarmSharp },
  { icon: alertSharp },
  { icon: boatSharp },
  { icon: bandageSharp },
  { icon: barChartSharp },
  { icon: desktopSharp },
  { icon: fishSharp },
  { icon: gameControllerSharp },
  { icon: home },
  { icon: man },
  { icon: lockClosedSharp },
  { icon: megaphoneSharp },
  { icon: newspaper },
  { icon: pawSharp },
  { icon: partlySunnySharp },
  { icon: schoolSharp },
  { icon: storefrontSharp },
  { icon: thermometerSharp },
  { icon: umbrellaSharp },
  { icon: woman },
  { icon: water },
  { icon: musicalNotesSharp },
  { icon: moonSharp },
  { icon: peopleSharp },
  { icon: telescopeSharp },
  { icon: thunderstormSharp },
  { icon: volumeMuteSharp },
  { icon: wifiSharp },
  { icon: settingsSharp },
  { icon: squareSharp },
  { icon: starSharp },
  { icon: homeSharp },
  { icon: cameraSharp },
  { icon: triangleSharp },
];
